[package]
name = "chinesebroad"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.189", features = ["derive"] }

[dependencies.bevy]
version = "0.11"
features = [
    "dynamic_linking",
    "mp3",
]

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3